### ISSUE TITLE
GenAI (formerly Prompt Design) launches in beta

### ISSUE THREAD

**Issue by 9ao9ai9ar** [samliew/se-timeline#27]
### What type of event change are you requesting

- [x] Add new event
- [ ] Update event details
- [ ] Remove event

**Checklist**

- [x] I have checked the spelling/grammar
- [x] I have verified that the date of the event is correct
- [x] I have verified all link references to ensure that they are not broken

---

If you are requesting a new event or updates to one, please provide either of the following:

### A. Paste Event JSON, or

If you created/edited this event using the [Event Editor](https://se-timeline.glitch.me/event-editor),
please paste the exported event JSON between the code backticks below:

```json
{
  "date_str": "2023-07-25",
  "title": "GenAI (formerly Prompt Design) launches in beta",
  "slug": "genai-formerly-prompt-design-launches-in-beta",
  "type": "site-launch",
  "body": "<p>It's notable in that it circumvented Area 51 and the normal procedure for establishing new sites, add to that the really suspicious timing of the site launch just days before the CEO's WeAreDevelopers World Congress talk.</p>",
  "links": [
    {
      "text": "MSE post",
      "url": "https://meta.stackexchange.com/q/390463"
    }
  ],
  "tags": [
    {
      "text": "prompt-design-site",
      "url": "https://meta.stackexchange.com/questions/tagged/prompt-design-site"
    }
  ]
},
```

### B. Describe the event

If you don't have an event JSON, please manually provide details of the event:

- Title
- Date (YYYY-MM-DD)
- Description
- Link(s)

**Comment by samliew** [comment]
Thanks for your contribution to the SE Timeline project.
