### ISSUE TITLE
Add linked event to "29 beta sites mass graduate"

### ISSUE THREAD

**Issue by 9ao9ai9ar** [samliew/se-timeline#29]
### What type of event change are you requesting

- [ ] Add new event
- [x] Update event details
- [ ] Remove event

**Checklist**

- [ ] I have checked the spelling/grammar
- [ ] I have verified that the date of the event is correct
- [ ] I have verified all link references to ensure that they are not broken

---

All 29 sites that graduated on August 1, 2019, should have a linked event to [29 beta sites mass graduate](https://meta.stackexchange.com/q/331708).

**Comment by samliew** [comment]
I don't see it as necessary, but if someone makes a PR for this I'm happy to merge.

**Comment by 9ao9ai9ar** [comment]
On second thought, you'd probably want to automate adding site graduation events by calling the [`/sites`](https://api.stackexchange.com/docs/sites) API directly.

**Comment by 9ao9ai9ar** [comment]
On third thought, I wonder how useful would GPT-4 be in coming up with its own Stack Exchange timeline so we can compare and cross-check for omissions.
