### ISSUE TITLE
Data dumps now hosted on the Internet Archive

### ISSUE THREAD

**Issue by 9ao9ai9ar** [samliew/se-timeline#30]
### What type of event change are you requesting

- [x] Add new event
- [ ] Update event details
- [ ] Remove event

**Checklist**

- [x] I have checked the spelling/grammar
- [x] I have verified that the date of the event is correct
- [x] I have verified all link references to ensure that they are not broken

---

```json
{
  "date_str": "2014-01-23",
  "title": "Data dumps now hosted on the Internet Archive",
  "slug": "data-dumps-now-hosted-on-the-internet-archive",
  "type": "data dump hosting",
  "body": "<p>The former host, ClearBits, permanently shut down at the end of 2013.</p><p>Links to all the data dump releases may be found in this <a href=\"https://meta.stackexchange.com/q/224873\">MSE post</a>.</p>",
  "icon": "https://archive.org/offshoot_assets/assets/ia-logo-2c2c2c.03bd7e88c8814d63d0fcb35fc01f37c3.svg",
  "links": [
    {
      "text": "blog post",
      "url": "https://stackoverflow.blog/2014/01/23/stack-exchange-cc-data-now-hosted-by-the-internet-archive/"
    }
  ]
},
```

**Comment by samliew** [comment]
I don't like that you are simply just copying the title of the blogpost and blockquoting the content.

Please import this back into the event editor and rewrite in your own words why this event is notable for the timeline readers.

Reopen when edited.

**Comment by 9ao9ai9ar** [comment]
@samliew Edited. Please review again, thanks.
