### ISSUE TITLE
Migration to in-house image hosting

### ISSUE THREAD

**Issue by 9ao9ai9ar** [samliew/se-timeline#31]
### What type of event change are you requesting

- [x] Add new event
- [ ] Update event details
- [ ] Remove event

**Checklist**

- [x] I have checked the spelling/grammar
- [x] I have verified that the date of the event is correct
- [x] I have verified all link references to ensure that they are not broken

---

```json
{
  "date_str": "2024-05-28",
  "title": "Migration to in-house image hosting",
  "slug": "migration-to-in-house-image-hosting",
  "type": "hosting",
  "summary": "all images migrated and hosted on `i.sstatic.net` (internal via CloudFlare)",
  "body": "<blockquote><a href=\"https://stackoverflow.blog/2010/08/18/new-image-upload-support\">Since 2010</a>, Imgur has provided image hosting services to Stack Exchange, but that hosting contract with Imgur comes to an end this upcoming April 2024. This April will conclude a 13-year-long successful relationship between Imgur and Stack, for which the whole company has been deeply grateful. However, Imgur no longer provides an enterprise image hosting product, and therefore, it has come time to find an alternative solution.<br />-- <a href=\"https://meta.stackexchange.com/users/1037447/slate\">Slate</a></blockquote>",
  "links": [
    {
      "text": "MSE post",
      "url": "https://meta.stackexchange.com/q/395024"
    }
  ]
},
```

**Comment by samliew** [comment]
This title is too long. Please rewrite in your own words/summarise it, and do not use an exact copy.

If using blockquotes, please also state the author name and link to their profile. Please refer to existing items for the format.

Reopen when edited.

**Comment by 9ao9ai9ar** [comment]
> This title is too long. Please rewrite in your own words/summarise it, and do not use an exact copy.
> 
> If using blockquotes, please also state the author name and link to their profile. Please refer to existing items for the format.
> 
> Reopen when edited.

Is there an actual limit on the length of the title, or are you just asking me to reword it better?

I see a lot of past events with blockquotes linking the author's name to the URL of an MSE post or a tweet. Is stating the author name and linking to their profile a new convention? If so, it'd be better to clarify it in the event editor.

@samliew Updated. Please review again, thanks.

**Comment by 9ao9ai9ar** [comment]
@samliew Pinging you again in case you didn't see it in the edit. I'd appreciate if you don't close the issues so fast and give me the opportunity to correct any problem. I may lose track of which suggested event updates haven't had a pull request merged in the pile of closed issues (the pull request icons aren't reliable indicators). Thank you again for taking my requests over the past 2 weeks as I'm nearly done with going over the timeline of Stack Exchange by now.

**Comment by samliew** [comment]
Thank you for your contribution to the SE timeline project
